DROP DATABASE IF EXISTS RESTAURANTE;

CREATE DATABASE RESTAURANTE;

USE RESTAURANTE;

CREATE TABLE CATEGORIA(
	cod CHAR(2) PRIMARY KEY,
	nombrec VARCHAR(20) UNIQUE,
	encargado VARCHAR(30),
	CONSTRAINT ck_nombrec CHECK (nombrec IN ('posre', 'primero', 'segundo', 'sin determinar'))
);

CREATE TABLE PLATO(
	codp INT PRIMARY KEY,
	nombrep VARCHAR(30) NOT NULL,
	descripcion TEXT,
	nivel int(1),
	precio DOUBLE(4,2),
	categoria VARCHAR(20) DEFAULT 'sin determinar',
	CONSTRAINT fk_categoria FOREIGN KEY (categoria) REFERENCES CATEGORIA (nombrec) ON DELETE SET DEFAULT,
	CONSTRAINT ck_precio CHECK (precio BETWEEN 8 AND 50),
	CONSTRAINT ck_nivel CHECK (nivel < 4)
);

CREATE TABLE INGREDIENTES(
	codigo INT PRIMARY KEY,
	nombre VARCHAR(20) NOT NULL UNIQUE,
	unidades VARCHAR(20),
	almacen INT
);

CREATE TABLE UTILIZA(
	codingr INT,
	codp INT,
	cantidad INT,
	CONSTRAINT pk_utiliza PRIMARY KEY (codingr, codp),
	CONSTRAINT fk_codingr FOREIGN KEY (codingr) REFERENCES INGREDIENTES (codigo) ON DELETE CASCADE,
	CONSTRAINT fk_codp FOREIGN KEY (codp) REFERENCES PLATO (codp) ON DELETE CASCADE
);

CREATE TABLE COCINERO(
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(30),
	fecha DATE
);

ALTER TABLE PLATO ADD cocinero INT, ADD CONSTRAINT fk_cocinero FOREIGN KEY (cocinero) REFERENCES COCINERO (id);

ALTER TABLE PLATO ADD fecha_creacion DATE DEFAULT (CURRENT_DATE);

ALTER TABLE COCINERO ADD sexo CHAR(2), ADD CONSTRAINT ck_sexo CHECK (sexo IN ('M', 'F', 'SD'));

ALTER TABLE INGREDIENTES MODIFY nombre VARCHAR(50);

ALTER TABLE PLATO DROP nivel;